schedules:
  - cron: '0 0 * * 1' # Run every Monday at midnight (UTC)
    branches:
      include:
        - main
    displayName: Weekly nx migrate weekly

trigger:
  - none

pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: RunScript
    steps:
      - script: |
          #!/bin/bash

          echo "Create feature branch"
          git checkout -b NFR/ALM/14_NxPluginsUpdate main

          echo "Install all packages"
          npm install

          NX_VERSION=$(npx nx --version)
          echo "Upgrade NX version $NX_VERSION"

          npx nx migrate latest

          if [ -f "migrations.json" ]; then
            echo "migrations.json found. Applying migration."
            npx nx migrate --run-migrations

            # Run npm audit fix to fix any security issues
            echo "Run audit fix --force to fix any security issues"
            npm audit fix --force

            # Run all tests
            echo "Run all tests"
            npx nx run-many -t test

            echo "Create commit"
            git add .
            git commit -m "chore: run nx migrate for @nx/workspace $NX_VERSION"

            echo "Push commit"
            git push origin feature-branch
          else
            echo "migrations.json not found. No migration to apply."
          fi

          # Create a pull request
          echo "Create pull request"
          git push --set-upstream origin feature-branch
          az repos pr create --description "Merge feature-branch into main" --target-branch main --source-branch feature-branch

        displayName: 'Run nx update package'
