site_name: Defra Digital Waste Tracking
site_url: https://defra.github.io/digital-waste-tracking
theme: 
  name: tech_docs_template
repo_url: https://github.com/DEFRA/digital-waste-tracking
remote_branch: gh-pages