apiVersion: v1
kind: Service
metadata:
  name: {{ include "waste-tracking-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waste-tracking-gateway.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.service.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "waste-tracking-gateway.selectorLabels" . | nindent 4 }}
