# Default values for address.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Custom labels for a deployment
labels: {}

# Number of pod replicas if horizontal pod autoscaler is not enable
replicaCount: 1

# Profile of the image used to create the pod containers
image:
  repository: sndwtshubcr3401.azurecr.io/address
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: '20230517.1'

# Exposed container port
targetPort: 5000

# Override the default name specified
nameOverride: ''
# Override the default full name specified
fullnameOverride: ''

# Profile of the service account used for Kubernetes auth
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    azure.workload.identity/tenant-id: '' # of the application MI
    azure.workload.identity/client-id: '' # of the application MI
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''
  labels:
    azure.workload.identity/use: 'true'

# Custom labels for a pod
podLabels:
  azure.workload.identity/use: 'true'

# Annotations on pod level
podAnnotations:
  dapr.io/enabled: 'true'
  # The client service will use this name to locate the Node service through the Dapr sidecar.
  dapr.io/app-id: 'address'
  # The port that your application is listening on
  dapr.io/app-port: '5000'
  dapr.io/enable-api-logging: 'true'
  dapr.io/log-level: 'debug'
  dapr.io/app-health-probe-interval: '3600'
  dapr.io/sidecar-liveness-probe-period-seconds: '3600'
  dapr.io/sidecar-readiness-probe-period-seconds: '3600'

# Container resource allocation
resources:
  limits:
    cpu: 50m
    memory: 128Mi

# Profile of the secret and values used for environment variable config
secret:
  name: ''
  env:
    APPINSIGHTS_CONNECTION_STRING: ''
    ADDRESS_LOOKUP_URL: ''
    CERT_FOLDER: ''
    CERT_NAME: ''

# Profile of the horizontal pod autoscaler used to create pod replicas
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  labels: {}

# Profile of the secret provider class used to mount secrets into the container from key vault
secretProviderClass:
  name: ''
  # ${USER_ASSIGNED_CLIENT_ID} of the workload identity
  clientId: ''
  keyVault:
    name: ''
    tenantId: ''

# TODO: from here and/or helpers.tpl
# objects:  |
#   array:
#     - |
#       objectName: boomi-api-tst-cert
#       objectType: cert
#       objectVersion: "" # [OPTIONAL] object versions, default to latest if empty

# Name used to reference the secrets mounted into the container from the key vault csi driver
volume:
  name: 'secrets-store01-inline'
  mountPath: ''
