parameters:
  - name: serviceConnection
    type: string
    default: ''
  - name: containerRegistryName
    type: string
    default: ''
  - name: appName
    type: string
    default: 'waste-tracking-service'
  - name: appNameTag
    type: string
    default: 'waste_tracking_service'
  - name: valuesFilePath
    type: string
    default: ''
  - name: appInsightsConnectionString
    type: string
    default: ''
  - name: dcidClientId
    type: string
    default: ''
  - name: dcidClientSecret
    type: string
    default: ''
  - name: dcidPolicy
    type: string
    default: ''
  - name: dcidRedirect
    type: string
    default: ''
  - name: dcidServiceId
    type: string
    default: ''
  - name: dcidTenant
    type: string
    default: ''
  - name: dcidWellKnown
    type: string
    default: ''
  - name: nextAuthSecret
    type: string
    default: ''
  - name: nextAuthUrl
    type: string
    default: ''

steps:
  - template: release.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      containerRegistryName: ${{ parameters.containerRegistryName }}
      appName: ${{ parameters.appName }}
      appNameTag: ${{ parameters.appNameTag }}

  - bash: |
      if [ $CHART_EXISTS == 'false' ]
      then
        echo "Installing release: ${PROJECT_NAME}"
        chartFullName="${HOST}/${PROJECT_NAME}"
        helm upgrade \
          --install $PROJECT_NAME \
          $chartFullName \
          --version $CHART_TAG \
          --create-namespace \
          -n $PROJECT_NAME \
          -f $VALUES_FILE_PATH \
          --set secret.env.APPINSIGHTS_CONNECTION_STRING=$APPINSIGHTS_CONNECTION_STRING \
          --set secret.env.DCID_CLIENT_ID=$DCID_CLIENT_ID \
          --set secret.env.DCID_CLIENT_SECRET=$DCID_CLIENT_SECRET \
          --set secret.env.DCID_POLICY=$DCID_POLICY \
          --set secret.env.DCID_REDIRECT=$DCID_REDIRECT \
          --set secret.env.DCID_SERVICE_ID=$DCID_SERVICE_ID \
          --set secret.env.DCID_TENANT=$DCID_TENANT \
          --set secret.env.DCID_WELLKNOWN=$DCID_WELLKNOWN \
          --set secret.env.NEXTAUTH_SECRET=$NEXTAUTH_SECRET \
          --set secret.env.NEXTAUTH_URL=$NEXTAUTH_URL
      else
        echo "Release: ${PROJECT_NAME} is already up to date"
      fi
    displayName: AKS Deploy ${{ parameters.appName }}
    env:
      AAD_SERVICE_PRINCIPAL_CLIENT_ID: $(spnClientId)
      AAD_SERVICE_PRINCIPAL_CLIENT_SECRET: $(spnClientSecret)
      HOST: oci://$(acr.loginServer)/charts/wts
      PROJECT_NAME: ${{ parameters.appName }}
      CHART_TAG: $(repository_${{ parameters.appNameTag }}.chartTag)
      VALUES_FILE_PATH: ${{ parameters.valuesFilePath }}
      APPINSIGHTS_CONNECTION_STRING: ${{ parameters.appInsightsConnectionString }}
      DCID_CLIENT_ID: ${{ parameters.dcidClientId }}
      DCID_CLIENT_SECRET: ${{ parameters.dcidClientSecret }}
      DCID_POLICY: ${{ parameters.dcidPolicy }}
      DCID_REDIRECT: ${{ parameters.dcidRedirect }}
      DCID_SERVICE_ID: ${{ parameters.dcidServiceId }}
      DCID_TENANT: ${{ parameters.dcidTenant }}
      DCID_WELLKNOWN: ${{ parameters.dcidWellKnown }}
      NEXTAUTH_SECRET: ${{ parameters.nextAuthSecret }}
      NEXTAUTH_URL: ${{ parameters.nextAuthUrl }}
      CHART_EXISTS: $(release_${{ parameters.appNameTag }}.exists)
