# https://github.com/diagrid-labs/dapr-on-aks
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
  namespace: dapr-demo
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: dapr-demo
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        # The client service will use this name to locate the Node service through the Dapr sidecar.
        dapr.io/app-id: "nodeapp"
        # The port that your application is listening on
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: node
        image: ghcr.io/dapr/samples/hello-k8s-node:latest
        resources:
          limits:
            memory: '128Mi'
            cpu: '50m'
        env:
        - name: APP_PORT
          value: "3000"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  namespace: dapr-demo
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pythonapp"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: python
        image: ghcr.io/dapr/samples/hello-k8s-python:latest
        resources:
          limits:
            memory: '128Mi'
            cpu: '50m'