apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-payment.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-payment.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service-payment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "service-payment.selectorLabels" . | nindent 8 }}
        {{- range $name, $value := .Values.podLabels }}
        {{ $name | quote }}: {{ $value | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "service-payment.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.targetPort }}
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:          
          {{- include "service-payment.env" . | nindent 8 }}

