image:
  tag: 'main'
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi
podAnnotations:
  dapr.io/sidecar-cpu-request: '1m'
  dapr.io/sidecar-cpu-limit: '5m'
  dapr.io/sidecar-memory-request: '64Mi'
  dapr.io/sidecar-memory-limit: '128Mi'
secret:
  env:
    CLIENT_ID: 'fe24d1fe9e0c9ab326e582ac3e1aca63'
    GLW_SURVEY_ID: 'SV_5p3VxHvybU0P7p4'
    UKWM_SURVEY_ID: 'SV_5b7HtKGCcwo2VNQ'
    SURVEY_API_ENDPOINT: 'https://fra1.qualtrics.com/'
