image:
  tag: 'sha-39d40e3'
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi
secret:
  env:
    COSMOS_DB_ACCOUNT_URI: 'https://devwtsinfco1401.documents.azure.com:443/'
serviceAccount:
  annotations:
    azure.workload.identity/client-id: 76846eaa-89fc-413a-8217-b969a4a7b7d5
    azure.workload.identity/tenant-id: c9d74090-b4e6-4b04-981d-e6757a160812
