# Default values for service-payment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Custom labels for a deployment
labels: {}

# Number of pod replicas if horizontal pod autoscaler is not enabled
replicaCount: 2

# Number of pods that should always be available and running
minAvailable: 1

# Profile of the image used to create the pod containers
image:
  repository: SSVWTSINFCR5401.azurecr.io/wts/service-payment
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'main'

# Exposed container port
targetPort: 3000

# Override the default name specified
nameOverride: ''
# Override the default full name specified
fullnameOverride: ''

# Profile of the service account used for Kubernetes auth
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    azure.workload.identity/tenant-id: '' # of the application MI
    azure.workload.identity/client-id: '' # of the application MI
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''
  labels:
    azure.workload.identity/use: 'true'

# Custom labels for a pod
podLabels:
  azure.workload.identity/use: 'true'

# Annotations on pod level
podAnnotations:
  dapr.io/enabled: 'true'
  # The client service will use this name to locate the Node service through the Dapr sidecar.
  dapr.io/app-id: 'service-payment'
  # The port that your application is listening on
  dapr.io/app-port: '3000'
  dapr.io/enable-api-logging: 'true'
  dapr.io/log-level: 'debug'
  dapr.io/app-health-probe-interval: '3600'
  dapr.io/sidecar-liveness-probe-period-seconds: '3600'
  dapr.io/sidecar-readiness-probe-period-seconds: '3600'
  dapr.io/sidecar-cpu-request: '1m'
  dapr.io/sidecar-cpu-limit: '5m'
  dapr.io/sidecar-memory-request: '64Mi'
  dapr.io/sidecar-memory-limit: '128Mi'

# Container resource allocation
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi

# Profile of the secret and values used for environment variable config
secret:
  name: ''
  env:
    APPINSIGHTS_CONNECTION_STRING: ''
    COSMOS_DB_ACCOUNT_URI: ''
    COSMOS_DATABASE_NAME: 'payment'
    COSMOS_DRAFTS_CONTAINER_NAME: 'drafts'
    COSMOS_SERVICE_CHARGE_CONTAINER_NAME: 'service-charges'
    GOVUK_PAY_API_URL: ''
    GOVUK_PAY_API_KEY: ''

# Profile of the horizontal pod autoscaler used to create pod replicas
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryAverageValue: 200Mi
  labels: {}
