parameters:
  - name: environment
    displayName: Environment under test
    default: DEV
    values:
      - DEV
      - TST
      - PRE

  - name: tags
    displayName: Filter expression for Cucumber scenarios
    type: string
    default: 'not @ignore and not @dev_only and not @code_display_issue'

  - name: parallelExecution
    displayName: Execute test suite in parallel?
    type: boolean
    default: true

  - name: numberOfThreads
    displayName: Number of parallel threads (only applicable if test suite is executed in parallel)
    type: number
    default: 4
    values:
      - 2
      - 3
      - 4

  - name: dependsOn
    displayName: Acceptance tests job dependencies
    type: object
    default: []

jobs:
  - job: test
    displayName: Acceptance tests

    dependsOn: ${{ parameters.dependsOn }}

    variables:
      - group: VG_${{ parameters.environment }}_APPS_PARAMS
      - name: startPageUrl
        value: https://track-waste-${{ lower(parameters.environment) }}.azure.defra.cloud/

    steps:
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 3.0'

      - bash: |
          gem install bundler
          bundle install

          mkdir -p reports/parallel

          echo "Parallel execution: $PARALLEL_EXECUTION"

          if [ "$PARALLEL_EXECUTION" = "False" ]; then
            echo "Executing acceptance tests on a single thread..."
            bundle exec cucumber \
              --color \
              --tags "$TAGS" \
              --format junit \
              --out junit \
              --format pretty \
            || echo "##vso[task.complete result=SucceededWithIssues;]"
          else
            echo "Executing acceptance tests in parallel on $NUMBER_OF_THREADS threads..."
            bundle exec parallel_cucumber \
              --type cucumber \
              -n $NUMBER_OF_THREADS \
              -o ' \
                --strict-undefined \
                --tags "$TAGS"  \
                --format junit \
                --out junit \
                --format pretty \
              ' \
              features/ \
            || echo "##vso[task.complete result=SucceededWithIssues;]"
          fi
        displayName: Run tests
        workingDirectory: tests/waste-tracking-service
        env:
          ENVIRONMENT: ${{ parameters.environment }}
          TAGS: ${{ parameters.tags }}
          PARALLEL_EXECUTION: ${{ parameters.parallelExecution }}
          NUMBER_OF_THREADS: ${{ parameters.numberOfThreads }}
          START_PAGE_URL: ${{ variables.startPageUrl }}
          USER_PASSWORD: $(testUserPassword)

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: tests/waste-tracking-service/junit/*.xml
        condition: always()
