parameters:
  - name: environment
    displayName: Environment under test
    default: DEV
    values:
      - DEV
      - TST
      - PRE

  - name: tags
    displayName: Filter expression for Cucumber scenarios
    type: string
    default: 'not @ignore and not @dev_only and not @code_display_issue'

jobs:
  - job: test
    displayName: Acceptance tests

    variables:
      - group: VG_${{ parameters.environment }}_APPS_PARAMS
      - name: startPageUrl
        value: https://track-waste-${{ lower(parameters.environment) }}.azure.defra.cloud/

    steps:
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 3.0'

      - bash: |
          gem install bundler
          bundle install

          mkdir -p reports/parallel

          bundle exec parallel_cucumber \
            --type cucumber \
            -n 4 \
            -o ' \
              --strict-undefined \
              --tags "$TAGS"  \
              --format junit \
              --out junit \
              --format pretty \
            ' \
            features/ \
          || echo "##vso[task.complete result=SucceededWithIssues;]"

        displayName: Run tests
        workingDirectory: tests/waste-tracking-service
        env:
          ENVIRONMENT: ${{ parameters.environment }}
          START_PAGE_URL: ${{ variables.startPageUrl }}
          USER_PASSWORD: $(testUserPassword)
          TAGS: ${{ parameters.tags }}

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: tests/waste-tracking-service/junit/*.xml
        condition: always()
