parameters:
  - name: acrServiceConnection
    type: string
    default: 'AZR-WTS-SSV5'
  - name: containerRegistryName
    type: string
    default: 'SSVWTSINFCR5401'
  - name: environment
    default: 'DEV'
    values:
      - SND
      - DEV
      - TST
      - PRE
      - PRD
  - name: manualDeployment
    type: boolean
    default: false

jobs:
  - ${{ if in(parameters.environment, 'SND', 'DEV', 'TST') }}:
      - deployment: restart_deployments
        displayName: Restart AKS Deployments
        environment: ${{ parameters.environment }}-Apps
        continueOnError: false
        ${{ if eq(parameters.manualDeployment, false) }}:
          condition: and(succeeded(), eq(stageDependencies.build.build_artifacts.outputs['publishContainers.affected'], 'true'))

        variables:
          - name: serviceConnection
            value: AZD-WTS-${{ parameters.environment }}1
          - name: aksName
            value: ${{ parameters.environment }}WTSINFAKS1401
          - name: resourceGroupName
            value: ${{ parameters.environment }}WTSINFRGP1401

        strategy:
          runOnce:
            deploy:
              steps:
                - template: auth/aks.yaml
                  parameters:
                    serviceConnection: ${{ variables.serviceConnection }}
                    aksName: ${{ variables.aksName }}
                    resourceGroupName: ${{ variables.resourceGroupName }}

                - ${{ if eq(parameters.manualDeployment, false) }}:
                    - download: current
                      artifact: runtimeVariables
                      displayName: Download runtime variables

                    - bash: |
                        affected=$(cat $(Pipeline.Workspace)/runtimeVariables/affectedProjects)
                        for project in ${affected//,/ }
                        do
                          echo "Restarting deployment: $project"
                          kubectl rollout restart deployment \
                            $project \
                            -n $project
                        done
                      displayName: AKS Restart Deployments
                      env:
                        AAD_SERVICE_PRINCIPAL_CLIENT_ID: $(spnClientId)
                        AAD_SERVICE_PRINCIPAL_CLIENT_SECRET: $(spnClientSecret)

                - ${{ else }}:
                    - bash: |
                        affected="api-waste-tracking-gateway,app-green-list-waste,app-uk-waste-movements,app-waste-tracking-service,service-address,service-green-list-waste-export,service-green-list-waste-export-bulk,service-feedback,service-limited-audience,service-reference-data"
                        for project in ${affected//,/ }
                        do
                          echo "Restarting deployment: $project"
                          kubectl rollout restart deployment \
                            $project \
                            -n $project
                        done
                      displayName: AKS Restart Deployments
                      env:
                        AAD_SERVICE_PRINCIPAL_CLIENT_ID: $(spnClientId)
                        AAD_SERVICE_PRINCIPAL_CLIENT_SECRET: $(spnClientSecret)

  - deployment: deploy_charts
    displayName: Deploy Helm Charts
    environment: ${{ parameters.environment }}-Apps
    continueOnError: false
    ${{ if eq(parameters.manualDeployment, false) }}:
      condition: and(succeeded(), eq(stageDependencies.build.build_artifacts.outputs['publishCharts.affected'], 'true'))

    variables:
      - group: VG_${{ parameters.environment }}_APPS_PARAMS
      - name: appList
        value: api-waste-tracking-gateway,app-green-list-waste,app-uk-waste-movements,app-waste-tracking-service,service-address,service-green-list-waste-export,service-green-list-waste-export-bulk,service-feedback,service-limited-audience,service-reference-data
      - name: serviceConnection
        ${{ if in(parameters.environment, 'SND', 'DEV', 'TST') }}:
          value: AZD-WTS-${{ parameters.environment }}1
        ${{ if in(parameters.environment, 'PRE', 'PRD') }}:
          value: AZR-WTS-${{ parameters.environment }}1
      - name: aksName
        value: ${{ parameters.environment }}WTSINFAKS1401
      - name: resourceGroupName
        value: ${{ parameters.environment }}WTSINFRGP1401

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              fetchDepth: 0

            - template: deploy/login.yaml
              parameters:
                acrServiceConnection: ${{ parameters.acrServiceConnection }}
                serviceConnection: ${{ variables.serviceConnection }}
                containerRegistryName: ${{ parameters.containerRegistryName }}
                aksName: ${{ variables.aksName }}
                resourceGroupName: ${{ variables.resourceGroupName }}

            - ${{ if eq(parameters.manualDeployment, false) }}:
                - download: current
                  artifact: runtimeVariables
                  displayName: Download runtime variables

                - bash: |
                    affected=$(cat $(Pipeline.Workspace)/runtimeVariables/affectedCharts)
                    if [[ $affected = *'api-waste-tracking-gateway'* ]]
                    then
                      echo "Deploy api-waste-tracking-gateway: true"
                      echo "##vso[task.setvariable variable=deployApiWasteTrackingGateway;isoutput=true]true"
                    else
                      echo "Deploy api-waste-tracking-gateway: false"
                      echo "##vso[task.setvariable variable=deployApiWasteTrackingGateway;isoutput=true]false"
                    fi
                    if [[ $affected = *'app-green-list-waste'* ]]
                    then
                      echo "Deploy app-green-list-waste: true"
                      echo "##vso[task.setvariable variable=deployAppGreenListWaste;isoutput=true]true"
                    else
                      echo "Deploy app-green-list-waste: false"
                      echo "##vso[task.setvariable variable=deployAppGreenListWaste;isoutput=true]false"
                    fi
                    if [[ $affected = *'app-uk-waste-movements'* ]]
                    then
                      echo "Deploy app-uk-waste-movements: true"
                      echo "##vso[task.setvariable variable=deployAppUkWasteMovements;isoutput=true]true"
                    else
                      echo "Deploy app-uk-waste-movements: false"
                      echo "##vso[task.setvariable variable=deployAppUkWasteMovements;isoutput=true]false"
                    fi
                    if [[ $affected = *'app-waste-tracking-service'* ]]
                    then
                      echo "Deploy app-waste-tracking-service: true"
                      echo "##vso[task.setvariable variable=deployAppWasteTrackingService;isoutput=true]true"
                    else
                      echo "Deploy app-waste-tracking-service: false"
                      echo "##vso[task.setvariable variable=deployAppWasteTrackingService;isoutput=true]false"
                    fi
                    if [[ $affected = *'service-address'* ]]
                    then
                      echo "Deploy service-address: true"
                      echo "##vso[task.setvariable variable=deployServiceAddress;isoutput=true]true"
                    else
                      echo "Deploy service-address: false"
                      echo "##vso[task.setvariable variable=deployServiceAddress;isoutput=true]false"
                    fi
                    if [[ $affected = *'service-green-list-waste-export'* ]]
                    then
                      echo "Deploy service-green-list-waste-export: true"
                      echo "##vso[task.setvariable variable=deployGreenListWasteExport;isoutput=true]true"
                    else
                      echo "Deploy service-green-list-waste-export: false"
                      echo "##vso[task.setvariable variable=deployGreenListWasteExport;isoutput=true]false"
                    fi
                    if [[ $affected = *'service-green-list-waste-export-bulk'* ]]
                    then
                      echo "Deploy service-green-list-waste-export-bulk: true"
                      echo "##vso[task.setvariable variable=deployGreenListWasteExportBulk;isoutput=true]true"
                    else
                      echo "Deploy service-green-list-waste-export-bulk: false"
                      echo "##vso[task.setvariable variable=deployGreenListWasteExportBulk;isoutput=true]false"
                    fi
                    if [[ $affected = *'service-feedback'* ]]
                    then
                      echo "Deploy service-feedback: true"
                      echo "##vso[task.setvariable variable=deployServiceFeedback;isoutput=true]true"
                    else
                      echo "Deploy service-feedback: false"
                      echo "##vso[task.setvariable variable=deployServiceFeedback;isoutput=true]false"
                    fi
                    if [[ $affected = *'service-limited-audience'* ]]
                    then
                      echo "Deploy service-limited-audience: true"
                      echo "##vso[task.setvariable variable=deployServiceLimitedAudience;isoutput=true]true"
                    else
                      echo "Deploy service-limited-audience: false"
                      echo "##vso[task.setvariable variable=deployServiceLimitedAudience;isoutput=true]false"
                    fi
                    if [[ $affected = *'service-reference-data'* ]]
                    then
                      echo "Deploy service-reference-data: true"
                      echo "##vso[task.setvariable variable=deployServiceReferenceData;isoutput=true]true"
                    else
                      echo "Deploy service-reference-data: false"
                      echo "##vso[task.setvariable variable=deployServiceReferenceData;isoutput=true]false"
                    fi
                  displayName: Helm chart deployment triggers
                  name: chart_triggers

            - ${{ each app in split(variables.appList, ',') }}:
                - ${{ if eq(app, 'api-waste-tracking-gateway') }}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        dcidClientId: $(dcidClientId)
                        dcidWellKnown: $(dcidWellKnown)
                        allowedUsers: $(allowedUsers)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployApiWasteTrackingGateway'], true)

                - ${{ elseif eq(app, 'app-green-list-waste')}}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        dcidClientId: $(dcidClientId)
                        dcidClientSecret: $(dcidClientSecret)
                        dcidPolicy: $(dcidPolicy)
                        dcidRedirect: $(dcidRedirect)
                        dcidServiceId: $(dcidServiceId)
                        dcidTenant: $(dcidTenant)
                        dcidWellKnown: $(dcidWellKnown)
                        nextAuthSecret: $(nextAuthSecret)
                        nextAuthUrl: $(nextAuthUrl)
                        nextPublicGoogleAnalyticsAccount: $(nextPublicGoogleAnalyticsAccount)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployAppGreenListWaste'], true)

                - ${{ elseif eq(app, 'app-uk-waste-movements')}}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployAppUkWasteMovements'], true)

                - ${{ elseif eq(app, 'app-waste-tracking-service')}}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        dcidClientId: $(dcidClientId)
                        dcidClientSecret: $(dcidClientSecret)
                        dcidPolicy: $(dcidPolicy)
                        dcidRedirect: $(dcidRedirect)
                        dcidServiceId: $(dcidServiceId)
                        dcidTenant: $(dcidTenant)
                        dcidWellKnown: $(dcidWellKnown)
                        nextAuthSecret: $(nextAuthSecret)
                        nextAuthUrl: $(nextAuthUrl)
                        nextPublicGoogleAnalyticsAccount: $(nextPublicGoogleAnalyticsAccount)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployAppWasteTrackingService'], true)

                - ${{ elseif eq(app, 'service-address') }}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployServiceAddress'], true)

                - ${{ elseif eq(app, 'service-green-list-waste-export') }}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployGreenListWasteExport'], true)

                - ${{ elseif eq(app, 'service-green-list-waste-export-bulk') }}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployGreenListWasteExportBulk'], true)

                - ${{ elseif eq(app, 'service-feedback') }}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        qualtricsClientSecret: $(qualtricsClientSecret)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployServiceFeedback'], true)

                - ${{ elseif eq(app, 'service-limited-audience') }}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        invitationTokenPublicKey: $(invitationTokenPublicKey)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployServiceLimitedAudience'], true)

                - ${{ elseif eq(app, 'service-reference-data') }}:
                    - template: deploy/${{ app }}.yaml
                      parameters:
                        serviceConnection: ${{ parameters.acrServiceConnection }}
                        containerRegistryName: ${{ parameters.containerRegistryName }}
                        valuesFilePath: ./pipelines/vars/${{ app }}/${{ lower(parameters.environment) }}.yaml
                        appInsightsConnectionString: $(appInsightsConnectionString)
                        ${{ if eq(parameters.manualDeployment, false) }}:
                          deployChart: eq(variables['chart_triggers.deployServiceReferenceData'], true)

                - ${{ else }}:
                    - bash: |
                        echo "Specify deployment template for: ${{ app }}"
                      displayName: Specify deployment template
