apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-payment.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-payment.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  {{- range $name, $value := .Values.secret.env }}
  {{ $name }}: {{ $value | b64enc }}
  {{- end}}
