trigger:
  - none

pool: DEFRA-COMMON-ubuntu2004-SSV3

parameters:
  - name: apps
    type: object
    default:
      - name: address
        nameTag: address
      - name: annex-vii
        nameTag: annex_vii
      - name: annex-vii-bulk
        nameTag: annex_vii_bulk
      - name: app-green-list-waste
        nameTag: app_green_list_waste
      - name: app-uk-waste-movements
        nameTag: app_uk_waste_movements
      - name: app-waste-tracking-service
        nameTag: app_waste_tracking_service
      - name: feedback
        nameTag: feedback
      - name: limited-audience
        nameTag: limited_audience
      - name: reference-data
        nameTag: reference_data
      - name: waste-tracking-gateway
        nameTag: waste_tracking_gateway

  - name: artifacts
    type: object
    default:
      - name: images
        prefix: wts
      - name: charts
        prefix: charts/wts

steps:
  - ${{ each app in parameters.apps }}:
      - ${{ each artifact in parameters.artifacts }}:
          - task: AzureCLI@2
            name: ${{ artifact.name }}_${{ app.nameTag }}
            displayName: ACR ${{ artifact.name }} ${{ app.name }}
            inputs:
              azureSubscription: AZR-WTS-SSV5
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                response=$(az acr repository show-tags \
                  --repository $REPOSITORY_NAME \
                  --orderby time_desc
                )
                echo $response | jq -r .[]
            env:
              AZURE_DEFAULTS_ACR: SSVWTSINFCR5401
              REPOSITORY_NAME: ${{ artifact.prefix }}/${{ app.name }}
