trigger:
  - none

pool: DEFRA-COMMON-ubuntu2004-SSV3

parameters:
  - name: apps
    type: object
    default:
      - name: api-waste-tracking-gateway
        nameTag: api_waste_tracking_gateway
      - name: app-green-list-waste-export
        nameTag: app_green_list_waste_export
      - name: app-uk-waste-movements
        nameTag: app_uk_waste_movements
      - name: app-waste-tracking-service
        nameTag: app_waste_tracking_service
      - name: service-address
        nameTag: service_address
      - name: service-green-list-waste-export
        nameTag: service_green_list_waste_export
      - name: service-green-list-waste-export-bulk
        nameTag: service_green_list_waste_export_bulk
      - name: service-feedback
        nameTag: service_feedback
      - name: service-limited-audience
        nameTag: service_limited_audience
      - name: service-reference-data
        nameTag: service_reference_data
      - name: service-uk-waste-movements
        nameTag: service_uk_waste_movements
      - name: service-uk-waste-movements-bulk
        nameTag: service_uk_waste_movements_bulk

  - name: artifacts
    type: object
    default:
      - name: images
        prefix: wts
      - name: charts
        prefix: charts/wts

steps:
  - ${{ each app in parameters.apps }}:
      - ${{ each artifact in parameters.artifacts }}:
          - task: AzureCLI@2
            name: ${{ artifact.name }}_${{ app.nameTag }}
            displayName: ACR ${{ artifact.name }} ${{ app.name }}
            inputs:
              azureSubscription: AZR-WTS-SSV5
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                response=$(az acr repository show-tags \
                  --repository $REPOSITORY_NAME \
                  --orderby time_desc
                )
                echo $response | jq -r .[]
            env:
              AZURE_DEFAULTS_ACR: SSVWTSINFCR5401
              REPOSITORY_NAME: ${{ artifact.prefix }}/${{ app.name }}
