trigger:
  - main

pool: DEFRA-COMMON-ubuntu2004-SSV3

parameters:
  - name: environments
    type: object
    default:
      - name: 'SND'
        dependsOn:
          - 'build'
        manualDeployment: false
      - name: 'DEV'
        dependsOn:
          - 'build'
          - 'SND'
        manualDeployment: false
      - name: 'TST'
        dependsOn:
          - 'build'
          - 'DEV'
        manualDeployment: false
      - name: 'PRE'
        dependsOn:
          - 'build'
          - 'TST'
        manualDeployment: false

stages:
  - stage: build
    displayName: Build

    jobs:
      - template: templates/build-artifacts.yaml

  - ${{ each environment in parameters.environments }}:
      - stage: ${{ environment.name }}
        displayName: ${{ environment.name }}
        ${{ if ne(environment.dependsOn, '') }}:
          dependsOn: ${{ environment.dependsOn }}

        ${{ if eq(environment.manualDeployment, False) }}:
          condition: and(succeeded(), or(eq(stageDependencies.build.outputs['build_artifacts.publishContainers.affected'], 'true'), eq(stageDependencies.build.outputs['build_artifacts.publishCharts.affected'], 'true')))

        jobs:
          - template: templates/deploy-apps.yaml
            parameters:
              environment: ${{ environment.name }}
              manualDeployment: ${{ environment.manualDeployment }}

  - stage: test
    displayName: Test

    jobs:
      - template: templates/acceptance-tests.yaml
        parameters:
          environment: DEV
