trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
 BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
 IMAGE_NAME: sndwtshubcr2401.azurecr.io/demo:1.0

steps:

- task: AzureCLI@1
  displayName: Login to ACR and list the registry
  inputs:
    connectedServiceNameARM: 'AZD-WTS-SND1'
    scriptLocation: 'inlineScript'   
    inlineScript: |
     az acr login -n SNDWTSHUBCR2401
- script: |
   npm ci
  displayName: 'npm ci'
- script: |
   npx nx container waste-tracking-service
  displayName: 'nx container waste-tracking-service'
- script: |
   docker image tag docker.io/wts/waste-tracking-service:$(BRANCH_NAME) $(IMAGE_NAME)
   docker image push $(IMAGE_NAME)
  displayName: Docker list, tag and push
- script: |
     kubectl apply -f workload.yaml
- task: AzureCLI@1
  displayName: install additional kubectl tools
  inputs:
    connectedServiceNameARM: 'AZD-WTS-SND1'
    scriptLocation: 'inlineScript'   
    inlineScript: |
     sudo az aks install-cli
     az aks get-credentials -n SNDWTSSPKKS1401 -g SNDWTSAKSRG1401
- task: Kubernetes@1
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: 'AZD-WTS-SND1'   
    azureResourceGroup: 'SNDWTSAKSRG1401'   
    kubernetesCluster: 'SNDWTSSPKKS1401' 
    command: 'apply'
    useConfigurationFile: true 
    configurationType: 'configuration' 
    configuration: '$(Build.SourcesDirectory)/pipelines/workload.yaml'  
    secretType: dockerRegistry
    containerRegistryType: Azure Container Registry 
    azureSubscriptionEndpointForSecrets: 'AZD-WTS-SND1' 
    azureContainerRegistry: 'sndwtshubcr2401.azurecr.io' 
    versionOrlocation: 'version'
    versionSpec: '1.24.9'
