trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
  - bash: npm ci
    name: dependencies
    displayName: Install dependencies

  - bash: |
      if ! npx nx format:check --all; then
        MSG='Some file are improperly formatted. See logs for a list.'
        echo "##vso[task.logissue type=error]$MSG"
        exit 1
      fi
    displayName: Check formatting
    condition: always()

  - bash: |
      if ! npx nx run-many --target=lint --all; then
        MSG='Lint errors found. See logs for a list.'
        echo "##vso[task.logissue type=error]$MSG"
        exit 1
      fi
    displayName: Linting
    condition: always()

  - bash: npx nx run-many --target=test --configuration=ci
    displayName: Unit Tests
    condition: always()

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: reports/junit/*.xml
    condition: always()

  - bash: npx nx run-many --target=build
    displayName: Build changed projects
    condition: always()
