trigger:
  - none

pool: DEFRA-COMMON-ubuntu2004-SSV3

parameters:
  - name: appName
    type: string
    default: app-green-list-waste-export
    values:
      - api-waste-tracking-gateway
      - app-green-list-waste-export
      - app-uk-waste-movements
      - app-waste-tracking-service
      - service-address
      - service-green-list-waste-export
      - service-green-list-waste-export-bulk
      - service-feedback
      - service-limited-audience
      - service-reference-data
  - name: tag
    type: string
    default: ''
  - name: releaseTag
    type: string
    default: ''

steps:
  - template: templates/auth/acr.yaml
    parameters:
      serviceConnection: AZR-WTS-SSV5
      containerRegistryName: SSVWTSINFCR5401

  - template: templates/auth/docker.yaml
    parameters:
      accessToken: $(acr.accessToken)
      loginServer: $(acr.loginServer)

  - bash: |
      source="${LOGIN_SERVER}/wts/${APP_NAME}:${TAG}"
      echo "Source artifacts: ${source}"
      release="${LOGIN_SERVER}/wts/${APP_NAME}:${RELEASE_TAG}"
      echo "Release artifacts: ${release}"
      docker pull $source
      docker tag $source $release
      docker push $release
    displayName: Create release tag
    env:
      LOGIN_SERVER: $(acr.loginServer)
      APP_NAME: ${{ parameters.appName }}
      TAG: ${{ parameters.tag }}
      RELEASE_TAG: ${{ parameters.releaseTag }}
