{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "feedback.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feedback.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.serviceAccount.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
