# Default values for service-green-list-waste-export-bulk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Custom labels for a deployment
labels: {}

# Number of pod replicas if horizontal pod autoscaler is not enable
replicaCount: 1

# Profile of the image used to create the pod containers
image:
  repository: SSVWTSINFCR5401.azurecr.io/wts/service-green-list-waste-export-bulk
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'main'

# Exposed container port
targetPort: 3000

# Override the default name specified
nameOverride: ''
# Override the default full name specified
fullnameOverride: ''

# Profile of the service account used for Kubernetes auth
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    azure.workload.identity/tenant-id: '' # of the application MI
    azure.workload.identity/client-id: '' # of the application MI
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''
  labels:
    azure.workload.identity/use: 'true'

# Custom labels for a pod
podLabels:
  azure.workload.identity/use: 'true'

# Annotations on pod level
podAnnotations:
  dapr.io/enabled: 'true'
  # The client service will use this name to locate the Node service through the Dapr sidecar.
  dapr.io/app-id: 'service-green-list-waste-export-bulk'
  # The port that your application is listening on
  dapr.io/app-port: '3000'
  dapr.io/enable-api-logging: 'true'
  dapr.io/log-level: 'debug'
  dapr.io/app-health-probe-interval: '3600'
  dapr.io/sidecar-liveness-probe-period-seconds: '3600'
  dapr.io/sidecar-readiness-probe-period-seconds: '3600'

# Container resource allocation
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi

# Profile of the secret and values used for environment variable config
secret:
  name: ''
  env:
    APPINSIGHTS_CONNECTION_STRING: ''
    COSMOS_DB_ACCOUNT_URI: ''
    COSMOS_DATABASE_NAME: 'annex-vii-bulk'
    COSMOS_DRAFTS_CONTAINER_NAME: 'drafts'
    SERVICE_BUS_HOST_NAME: ''
    TASKS_QUEUE_NAME: 'annex-vii-bulk-tasks'
    GLW_EXPORT_APP_ID: 'service-green-list-waste-export.service-green-list-waste-export'

# Profile of the horizontal pod autoscaler used to create pod replicas
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  labels: {}
