image:
  tag: 'main'
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi
podAnnotations:
  dapr.io/sidecar-cpu-request: '1m'
  dapr.io/sidecar-cpu-limit: '5m'
  dapr.io/sidecar-memory-request: '64Mi'
  dapr.io/sidecar-memory-limit: '128Mi'
secret:
  env:
    COSMOS_DB_ACCOUNT_URI: 'https://devwtsinfco1401.documents.azure.com:443/'
serviceAccount:
  annotations:
    azure.workload.identity/client-id: dc7a252c-371b-4b4c-8c97-afcdd3afa28e
    azure.workload.identity/tenant-id: c9d74090-b4e6-4b04-981d-e6757a160812
