apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app-uk-waste-movements.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-uk-waste-movements.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  minAvailable: {{ include "app-uk-waste-movements.pdbMinAvailable" . }}
  selector:
    matchLabels:
      {{- include "app-uk-waste-movements.selectorLabels" . | nindent 6 }}