apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-uk-waste-movements.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-uk-waste-movements.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.service.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "app-uk-waste-movements.selectorLabels" . | nindent 4 }}
