# Default values for waste-tracking-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Custom labels for a deployment
labels: {}

# Number of pod replicas if horizontal pod autoscaler is not enable
replicaCount: 2

# Profile of the image used to create the pod containers
image:
  repository: SSVWTSINFCR5401.azurecr.io/wts/app-waste-tracking-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'main'

# Override the default name specified
nameOverride: ''
# Override the default full name specified
fullnameOverride: ''

# Profile of the service account used for Kubernetes auth
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    {}
    # Required for using Managed Identities on pod level
    # azure.workload.identity/client-id: USER_ASSIGNED_CLIENT_ID # of the application MI
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''
  labels:
    {}
    # Required for using Managed Identities on pod level
    # azure.workload.identity/use: "true"

# Custom labels for a pod
podLabels:
  {}
  # Required for using Managed Identities on pod level
  # azure.workload.identity/use: "true"

# Annotations on pod level
podAnnotations: {}

# Container resource allocation
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi

# Profile of the secret and values used for environment variable config
secret:
  name: ''
  env:
    APPINSIGHTS_CONNECTION_STRING: ''
    DCID_CLIENT_ID: ''
    DCID_CLIENT_SECRET: ''
    DCID_POLICY: ''
    DCID_REDIRECT: ''
    DCID_SERVICE_ID: ''
    DCID_TENANT: ''
    DCID_WELLKNOWN: ''
    NEXTAUTH_SECRET: ''
    NEXTAUTH_URL: ''
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ACCOUNT: ''
    NEXT_PUBLIC_MULTIPLES_ENABLED: 'false'
    NEXT_PUBLIC_LANGUAGES_ENABLED: 'false'

# Profile of the horizontal pod autoscaler used to create pod replicas
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  labels: {}

# Profile of the service exposing containers
service:
  type: ClusterIP
  port: 80
  # Exposed container port
  targetPort: 3000
  labels: {}

# Profile of the ingress exposing apps outside of the cluster
ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: 'wts-uksbe-snd.azure.defra.cloud'
      paths:
        - path: /
          pathType: Prefix
  labels: {}
