parameters:
  - name: serviceConnection
    type: string
    default: ''
  - name: containerRegistryName
    type: string
    default: ''
  - name: appName
    type: string
    values:
      - waste-tracking-service
      - waste-tracking-gateway
      - annex-vii
      - address
      - reference-data
  - name: appNameTag
    type: string
    values:
      - waste_tracking_service
      - waste_tracking_gateway
      - annex_vii
      - address
      - reference_data
  - name: deployChart
    type: string
    default: ''

steps:
  - task: AzureCLI@2
    name: repository_${{ parameters.appNameTag }}
    displayName: ACR repository ${{ parameters.appName }}
    condition: ${{ parameters.deployChart }}
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        response=$(az acr repository show-tags \
          --repository $REPOSITORY_NAME \
          --orderby time_desc \
          --top 1
        )
        echo "Latest Helm chart tag for: ${REPOSITORY_NAME}"
        echo $response | jq -r .[]
        echo "##vso[task.setvariable variable=chartTag;isoutput=true]$( \
          echo $response | jq -r .[] \
        )"
    env:
      AZURE_DEFAULTS_ACR: ${{ parameters.containerRegistryName }}
      REPOSITORY_NAME: charts/wts/${{ parameters.appName }}
