parameters:
  - name: serviceConnection
    type: string
    default: ''
  - name: containerRegistryName
    type: string
    default: ''
  - name: appName
    type: string
    values:
      - api-waste-tracking-gateway
      - app-green-list-waste-export
      - app-uk-waste-movements
      - app-waste-tracking-service
      - service-address
      - service-green-list-waste-export
      - service-green-list-waste-export-bulk
      - service-feedback
      - service-limited-audience
      - service-reference-data
  - name: appNameTag
    type: string
    values:
      - api_waste_tracking_gateway
      - app_green_list_waste_export
      - app_uk_waste_movements
      - app_waste_tracking_service
      - service_address
      - service_green_list_waste_export
      - service_green_list_waste_export_bulk
      - service_feedback
      - service_limited_audience
      - service_reference_data
  - name: deployChart
    type: string
    default: ''

steps:
  - task: AzureCLI@2
    name: repository_${{ parameters.appNameTag }}
    displayName: ACR repository ${{ parameters.appName }}
    condition: ${{ parameters.deployChart }}
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        response=$(az acr repository show-tags \
          --repository $REPOSITORY_NAME \
          --orderby time_desc \
          --top 1
        )
        echo "Latest Helm chart tag for: ${REPOSITORY_NAME}"
        echo $response | jq -r .[]
        echo "##vso[task.setvariable variable=chartTag;isoutput=true]$( \
          echo $response | jq -r .[] \
        )"
    env:
      AZURE_DEFAULTS_ACR: ${{ parameters.containerRegistryName }}
      REPOSITORY_NAME: charts/wts/${{ parameters.appName }}
