apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "service-address.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-address.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  minAvailable: {{ include "service-address.pdbMinAvailable" . }}
  selector:
    matchLabels:
      {{- include "service-address.selectorLabels" . | nindent 6 }}