image:
  tag: 'main'
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi
ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: 'wts-uksbe-dev.azure.defra.cloud'
      paths:
        - path: /move-waste
          pathType: Prefix
