apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-tracking-service-deploy
spec:
  selector:
    matchLabels:
      app: waste-tracking-service-deploy
  template:
    metadata:
      labels:
        app: waste-tracking-service-deploy
    spec:
      containers:
      - name: waste-tracking-service-deploy
        image: sndwtshubcr2401.azurecr.io/demo:1.0  #  ${IMAGE_NAME}
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: waste-tracking-service-svc
spec:
  selector:
    app: waste-tracking-service-svc
  ports:
  - port: 8080
    targetPort: 3000
