openapi: '3.0.3'
info:
  title: Digital Waste Tracking Collection API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /movements:
    post:
      description: Endpoint to be used by the carrier to create a new route/round/movement prior to delivering the waste to the receiver. The round can contain multiple collections but is a single delivery to a receiver.
                   This endpoint can contain all of the stops in the movement or they can be added separately.
      responses:
        '200':
          description: OK
  /movements/{id}:
    patch:
      description: Endpoint to be used by the carrier to add details of a movement which was delivered to the receiver without a waste tracking id.
                   The same endpoint would also be used if the carrier has created the tracking record but the details need to be subsequently amended.
      responses:
        '200':
          description: OK
  /movements/{id}/stop:
    post:
      description: Add a stop where waste will be collected to the overall movement.
  /movements/{id}/stop/{stopid}:
    patch:
      description: Amend the details of a stop.
    delete:
      description: Remove a stop from the waste movement.