apiVersion: v1
kind: Service
metadata:
  name: {{ include "annex-vii.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "annex-vii.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.service.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "annex-vii.selectorLabels" . | nindent 4 }}
