apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uk-waste-movements.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uk-waste-movements.labels" . | nindent 4 }}
    {{- range $name, $value := .Values.labels }}
    {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "uk-waste-movements.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uk-waste-movements.selectorLabels" . | nindent 8 }}
        {{- range $name, $value := .Values.podLabels }}
        {{ $name | quote }}: {{ $value | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "uk-waste-movements.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:          
          {{- include "uk-waste-movements.env" . | nindent 8 }}
