# Default values for api-waste-tracking-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Custom labels for a deployment
labels: {}

# Number of pod replicas if horizontal pod autoscaler is not enable
replicaCount: 1

# Profile of the image used to create the pod containers
image:
  repository: SSVWTSINFCR5401.azurecr.io/wts/api-waste-tracking-gateway
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'main'

# Override the default name specified
nameOverride: ''
# Override the default full name specified
fullnameOverride: ''

# Profile of the service account used for Kubernetes auth
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    {}
    # Required for using Managed Identities on pod level
    # azure.workload.identity/client-id: USER_ASSIGNED_CLIENT_ID # of the application MI
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''
  labels:
    {}
    # Required for using Managed Identities on pod level
    # azure.workload.identity/use: "true"

# Custom labels for a pod
podLabels:
  {}
  # Required for using Managed Identities on pod level
  # azure.workload.identity/use: "true"

# Annotations on pod level
podAnnotations:
  dapr.io/enabled: 'true'
  # The client service will use this name to locate the Node service through the Dapr sidecar.
  dapr.io/app-id: 'api-waste-tracking-gateway'
  dapr.io/enable-api-logging: 'true'
  dapr.io/log-level: 'debug'
  dapr.io/app-health-probe-interval: '3600'
  dapr.io/sidecar-liveness-probe-period-seconds: '3600'
  dapr.io/sidecar-readiness-probe-period-seconds: '3600'

# Container resource allocation
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi

# Profile of the secret and values used for environment variable config
secret:
  name: ''
  env:
    APPINSIGHTS_CONNECTION_STRING: ''
    GLW_EXPORT_APP_ID: 'service-green-list-waste-export.service-green-list-waste-export'
    GLW_EXPORT_BULK_APP_ID: 'service-green-list-waste-export-bulk.service-green-list-waste-export-bulk'
    ADDRESS_APP_ID: 'service-address.service-address'
    FEEDBACK_APP_ID: 'service-feedback.service-feedback'
    LIMITED_AUDIENCE_APP_ID: 'service-limited-audience.service-limited-audience'
    REFERENCE_DATA_APP_ID: 'service-reference-data.service-reference-data'
    UKWM_BULK_APP_ID: 'service-uk-waste-movements-bulk.service-uk-waste-movements-bulk'
    DCID_CLIENT_ID: ''
    DCID_WELLKNOWN: ''
    ALLOWED_USERS: ''
    IS_MULTIPLE_UPLOAD_ENABLED: 'false'
    IS_AUTO_EMAIL_CONFIRMATION_ENABLED: 'false'
    FEATURE_PRIVATE_AUDIENCE_CHECKS: 'false'
    IS_UKWM_BATCHES_ENABLED: 'false'

# Profile of the horizontal pod autoscaler used to create pod replicas
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  labels: {}

# Profile of the service exposing containers
service:
  type: ClusterIP
  port: 80
  # Exposed container port
  targetPort: 3000
  labels: {}

# Profile of the ingress exposing apps outside of the cluster
ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: 'wts-uksbe-snd.azure.defra.cloud'
      paths:
        - path: /api/submissions
          pathType: Prefix
        - path: /api/addresses
          pathType: Prefix
        - path: /api/templates
          pathType: Prefix
        - path: /api/reference-data
          pathType: Prefix
        - path: /api/batches
          pathType: Prefix
        - path: /api/feedback
          pathType: Prefix
        - path: /api/privatebeta
          pathType: Prefix
        - path: /api/ukwm-batches
          pathType: Prefix
  labels: {}
