name: Deploy Versioned Documentation

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material mike

      - name: Deploy documentation
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          set -euo pipefail
          echo "Deploying ${VERSION} documentation"
          mike deploy --push --remote origin --branch gh-pages --update-aliases "${VERSION}" latest
          mike set-default --push --remote origin --branch gh-pages latest
